### ISSUE TITLE
setup.py not found error

### ISSUE THREAD

**Issue by huertanix** [simonft/phrasebook#8]
When running through build instructions in macOS High Sierra, all build commands seem to work up until `pip install -e .[dev]` is ran. A `Directory '.' is not installable. File 'setup.py' not found.` error shows up and pip doesn't end up installing anything.

**Comment by simonft** [comment]
Hmm, that's strange. Are you sure you ran the `cd phrasebook` in the instructions (exactly once)? You'll need to be in the root directory that `git clone phrasebook` created. 

If you are in fact running it from that directory, can you paste the full output of these commands?

```
pwd
ls
pip install -e .[dev]
```

I also made a change in cb5d50cc7027d659099d5d2e2f291d351cd5c128 to fix an unrelated issue. You'll likely need to rm and re-add the venv directory for the change to take effect.

**Comment by huertanix** [comment]
I found out I accidentally cd'd into the `phrasebook` directory inside the `phrasebook` directory and created a second `venv` directory by accident. My terminal settings are pretty basic so my prompt only shows the name of the current directory and not any of its parent directories. I hadn't noticed there were two nested `phrasebook` directories.

**Comment by simonft** [comment]
Great! I think this means I can close the issue. Please feel free to re-open it if that's not the case.
